export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const PROJECTS_ERROR = "PROJECTS_ERROR";
export const ADD_PROJECT = "ADD_PROJECT";
export const CLOSE_PROJECT = "CLOSE_PROJECT";
